# Generated by Django 3.0.5 on 2022-09-22 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=1024)),
                ('sha', models.CharField(max_length=64)),
                ('bench', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osname', models.CharField(max_length=128)),
                ('threads', models.IntegerField(default=0)),
                ('mnps', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lastaddr', models.CharField(default='None', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('sha256', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('engine', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('engine', models.CharField(max_length=64)),
                ('test_mode', models.CharField(default='SPRT', max_length=16)),
                ('source', models.CharField(max_length=1024)),
                ('devoptions', models.CharField(max_length=256)),
                ('baseoptions', models.CharField(max_length=256)),
                ('devnetwork', models.CharField(max_length=256)),
                ('basenetwork', models.CharField(max_length=256)),
                ('devnetname', models.CharField(max_length=256)),
                ('basenetname', models.CharField(max_length=256)),
                ('bookname', models.CharField(max_length=32)),
                ('timecontrol', models.CharField(max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('throughput', models.IntegerField(default=0)),
                ('syzygy_adj', models.CharField(default='OPTIONAL', max_length=16)),
                ('syzygy_wdl', models.CharField(default='OPTIONAL', max_length=16)),
                ('elolower', models.FloatField(default=0.0)),
                ('eloupper', models.FloatField(default=0.0)),
                ('alpha', models.FloatField(default=0.0)),
                ('beta', models.FloatField(default=0.0)),
                ('lowerllr', models.FloatField(default=0.0)),
                ('currentllr', models.FloatField(default=0.0)),
                ('upperllr', models.FloatField(default=0.0)),
                ('max_games', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('error', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base', to='OpenBench.Engine')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev', to='OpenBench.Engine')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('crashes', models.IntegerField(default=0)),
                ('timeloss', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine', to='OpenBench.Machine')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test', to='OpenBench.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('tests', models.IntegerField(default=0)),
                ('repo', models.CharField(blank=True, max_length=256)),
                ('engine', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('approver', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='workload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workload', to='OpenBench.Test'),
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=64)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test1', to='OpenBench.Test')),
            ],
        ),
    ]
