# Generated by Django 3.0.5 on 2022-09-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logevent',
            old_name='creation',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='logevent',
            name='data',
        ),
        migrations.RemoveField(
            model_name='logevent',
            name='test',
        ),
        migrations.AddField(
            model_name='logevent',
            name='log_file',
            field=models.CharField(default='nofile', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logevent',
            name='machine_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logevent',
            name='summary',
            field=models.CharField(default='nosum', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logevent',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logevent',
            name='author',
            field=models.CharField(max_length=128),
        ),
    ]
