# Generated by Django 4.2.1 on 2023-12-31 13:43
# modified by meeeee :3

from django.db import migrations, models
from datetime import datetime, timezone

def send_machines_to_1970(apps, _schema_editor):
    Machine = apps.get_model("OpenBench", "Machine")
    Machine.objects.all().update(updated=datetime.fromtimestamp(0, timezone.utc))

def update_profile_repo(apps, _schema_editor):
    Profile = apps.get_model("OpenBench", "Profile")
    for profile in Profile.objects.all():
        profile.repos[profile.engine] = profile.repo
        profile.save()

def update_test_fields(apps, _schema_editor):
    Test = apps.get_model("OpenBench", "Test")
    for test in Test.objects.all():
        test.use_penta = False
        test.use_tri = True
        test.dev_repo = test.base_repo
        test.dev_engine = test.base_engine
        test.dev_time_control = test.base_time_control
        test.save()

class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0002_auto_20220922_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=0)),
                ('result_id', models.IntegerField(default=0)),
                ('book_index', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),

        # profile changes
        migrations.AddField(
            model_name='profile',
            name='repos',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RunPython(update_profile_repo),
        migrations.RemoveField(
            model_name='profile',
            name='repo',
        ),

        # network changes
        migrations.AddField(
            model_name='network',
            name='was_default',
            field=models.BooleanField(default=False),
        ),

        # result changes
        migrations.AddField(
            model_name='result',
            name='DD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='DW',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='LD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='LL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='WW',
            field=models.IntegerField(default=0),
        ),  

        # machine changes
        migrations.AddField(
            model_name='machine',
            name='secret',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='base_mnps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='dev_mnps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='machine',
            name='lastaddr',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='osname',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='threads',
        ),
        migrations.AlterField(
            model_name='machine',
            name='workload',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(send_machines_to_1970),


        # test changes (the horrible part)

        # penta stuff
        migrations.AddField(
            model_name='test',
            name='DD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='DW',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='LD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='LL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='WW',
            field=models.IntegerField(default=0),
        ),

        # all of the casing renames that shouldn't really matter
        migrations.RenameField(
            model_name='test',
            old_name='basenetname',
            new_name='base_netname',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='basenetwork',
            new_name='base_network',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='baseoptions',
            new_name='base_options',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='bookname',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='devnetname',
            new_name='dev_netname',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='devnetwork',
            new_name='dev_network',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='devoptions',
            new_name='dev_options',
        ),

        # I have no idea what any of these fields are but they don't seem to correspond to any older field
        migrations.AddField(
            model_name='test',
            name='awaiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='book_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='draw_adj',
            field=models.CharField(default='movenumber=40 movecount=8 score=10', max_length=64),
        ),
        migrations.AddField(
            model_name='test',
            name='spsa',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='upload_pgns',
            field=models.CharField(default='FALSE', max_length=16),
        ),
        migrations.AddField(
            model_name='test',
            name='use_penta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='use_tri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='win_adj',
            field=models.CharField(default='movecount=3 score=400', max_length=64),
        ),
        migrations.AddField(
            model_name='test',
            name='workload_size',
            field=models.IntegerField(default=32),
        ),


        # split timecontrol
        migrations.AlterField(
            model_name='test',
            name='timecontrol',
            field=models.CharField(max_length=32),
        ),
        migrations.RenameField(
            model_name='test',
            old_name='timecontrol',
            new_name='base_time_control',
        ),
        migrations.AddField(
            model_name='test',
            name='dev_time_control',
            field=models.CharField(default='devtc', max_length=32),
            preserve_default=False,
        ),

        # split engine
        migrations.RenameField(
            model_name='test',
            old_name='engine',
            new_name='base_engine',
        ),
        migrations.AddField(
            model_name='test',
            name='dev_engine',
            field=models.CharField(default='devengine', max_length=64),
            preserve_default=False,
        ),

        # split source
        migrations.RenameField(
            model_name='test',
            old_name='source',
            new_name='base_repo',
        ),
        migrations.AddField(
            model_name='test',
            name='dev_repo',
            field=models.CharField(default='devrepo', max_length=1024),
            preserve_default=False,
        ),

        migrations.RunPython(update_test_fields),
    ]
